### ISSUE TITLE
will suika2 add debug tools back

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#27]
I tried catsystem2 ,it has a window to jump to different script,I want to know will suika2 add those tools back?

**Comment by ktabata** [comment]
Hi,
On Suika2, we have `load` command to jump to different script.
Isn't it enough?
What do you mean for "window"?

**Comment by ishani-rgb** [comment]
The scripting language is so simple and easy that I doubt its needed.

**Comment by 2439905184** [comment]
I like suika2,but I haven't have time to learn suika2's code carefully.I saw the source code file numbers are not very much.
I think learn it maybe easy.If I have enough free time ,I think I will learn its code .

**Comment by lochana-Dineko** [comment]
Happy to see that Suika2's clean and efficient programming also future proofs it to a degree. I specifically have experience with Ponscripters older brother Onscripter-en, and had to give up on maintaining it because it was too complex to work with.

Since Suika2's code is so simple I've been experimenting with using Suika 2 to port Older Visual Novel games to new machines. Instead of creating a new engine, creating a script to convert the given script to Suika 2 Script is convenient.

**Comment by ktabata** [comment]
Hi @lochana-Dineko,

It's good news to hear that Suika2 runs on Tiny7.
Suika2 actually supports Windows XP/7/8/8.1/10/11.
It uses _align_malloc() and _align_free(), and these APIs are supported at XP.

If you just write `#undef SSE_VERSIONING` in `types.h`, Suika2 will run on Windows 95 and 98 ;-)
![suika2-win98](https://user-images.githubusercontent.com/2771164/142289297-0517a482-b739-4193-8895-d16812ef4d64.png)

**Comment by lochana-Dineko** [comment]
> Hi @lochana-Dineko,
> 
> It's good news to hear that Suika2 runs on Tiny7. Suika2 actually supports Windows XP/7/8/8.1/10/11. It uses _align_malloc() and _align_free(), and these APIs are supported at XP.
> 
> If you just write `#undef SSE_VERSIONING` in `types.h`, Suika2 will run on Windows 95 and 98 ;-)
> 
> ![suika2-win98](https://user-images.githubusercontent.com/2771164/142289297-0517a482-b739-4193-8895-d16812ef4d64.png)

Holy backwards compatibility batman!
That's awesome.
That speaks to the strength of the code.
