### ISSUE TITLE
will suika2 add plugin function?

### ISSUE THREAD

**Issue by 2439905184** [ktabata/suika2#33]
I suddenly thinked about this,I saw a tutorail video about kirikiri engine.He say the krkr engine can add and use plugin (dll)。
I noticed the effect plugin is about falling snow.It can use in game in Winter season。

**Comment by ktabata** [comment]
Suika2 will not use plugin DLLs because it runs on both Windows and Mac.
For Mac, we have to prepare dylib but it's not user friendly.
If someone is developing a real game and wants some effects, I'll implement it for both Windows and Mac.
In fact, I recently implemented eye-open effect by a request from a user.

**Comment by lochana-Dineko** [comment]
> I suddenly thinked about this,I saw a tutorail video about kirikiri engine.He say the krkr engine can add and use plugin (dll)。 I noticed the effect plugin is about falling snow.It can use in game in Winter season。

Hold on.
Doesn't KiriKiri use a simple snow.ks plugin script instead of a DLL? That's what I used when I was working with KiriKiri. KiriKiri only needs external DLLs for some extremely advanced functions. Snow.ks and Rain.ks scripts don't need any external DLLs to work.

However Nscripter does use DLLs. That is now obsolete and Onscripter and Ponscripter, it's open source descendents use hard coded effects like Suika.
